/* fmath.c - SQR / SIN / COS / TAN built on the MBF engine.
 *
 * SQR: Newton-Raphson, seeded by halving the binary exponent (within 2x of
 * the root, so 5 iterations converge past 24 bits).
 * SIN/COS: range-reduce by k = round(x * 2/pi), r = x - k*(pi/2) (|r| <= pi/4),
 * then a 4-term polynomial; the quadrant picks sin/cos polynomial and sign -
 * cos(x) just evaluates with the quadrant shifted by one.
 * All constants are packed MBF generated by tools/mbf.py.
 */
#include "basrun.h"

static const num_t C_PIH  = {{0xDB, 0x0F, 0x49, 0x81}};  /* pi/2 */
static const num_t C_2OPI = {{0x83, 0xF9, 0x22, 0x80}};  /* 2/pi */
static const num_t C_S3   = {{0xAB, 0xAA, 0xAA, 0x7E}};  /* -1/6 */
static const num_t C_S5   = {{0x89, 0x88, 0x08, 0x7A}};  /* 1/120 */
static const num_t C_S7   = {{0x01, 0x0D, 0xD0, 0x74}};  /* -1/5040 */
static const num_t C_C2   = {{0x00, 0x00, 0x80, 0x80}};  /* -1/2 */
static const num_t C_C4   = {{0xAB, 0xAA, 0x2A, 0x7C}};  /* 1/24 */
static const num_t C_C6   = {{0x61, 0x0B, 0xB6, 0x77}};  /* -1/720 */
static const num_t C_ONE  = {{0x00, 0x00, 0x00, 0x81}};  /* 1.0 */

static num_t fx, fy, fr, fr2;

void fn_sqr(void)
{
    signed char s = f_sgn(), e;
    unsigned char i;
    if (s < 0) { err(E_IFC); return; }
    if (s == 0) return;
    f_st(&fx);
    e = f_exp();
    f_ld(&fx);
    f_scale((signed char)((e >> 1) - e));   /* seed ~ m * 2^(e/2) */
    f_st(&fy);
    for (i = 0; i < 5; i++) {               /* y = (y + x/y) / 2 */
        f_ld(&fx);
        f_arg(&fy);
        f_div();
        f_arg(&fy);
        f_add();
        f_scale(-1);
        f_st(&fy);
    }
    f_ld(&fy);
}

/* redq: FAC = x -> FAC = r (|r| <= pi/4); returns the quadrant (k+add1) & 3 */
static unsigned char redq(unsigned char add1)
{
    int k;
    f_st(&fx);
    f_arg(&C_2OPI);
    f_mul();
    k = f_toi();                             /* rounds to nearest */
    f_fromi(k);
    f_arg(&C_PIH);
    f_mul();
    f_st(&fy);
    f_ld(&fx);
    f_arg(&fy);
    f_sub();                                 /* FAC = r */
    return (unsigned char)(((unsigned int)k + add1) & 3);
}

/* poly: FAC = ((c*r2 + b)*r2 + a)*r2 + 1  (fr2 must hold r^2) */
static void poly(const num_t *a, const num_t *b, const num_t *c)
{
    f_ld(c);
    f_arg(&fr2); f_mul(); f_arg(b); f_add();
    f_arg(&fr2); f_mul(); f_arg(a); f_add();
    f_arg(&fr2); f_mul(); f_arg(&C_ONE); f_add();
}

static void sincos(unsigned char add1)
{
    unsigned char q = redq(add1);
    if (g_err || fac_err) return;
    f_st(&fr);
    f_arg(&fr);
    f_mul();
    f_st(&fr2);                              /* r^2 */
    if (q & 1) {
        poly(&C_C2, &C_C4, &C_C6);           /* cos(r) */
    } else {
        poly(&C_S3, &C_S5, &C_S7);           /* sin(r)/r */
        f_arg(&fr);
        f_mul();
    }
    if (q & 2) f_neg();
}

void fn_sin(void) { sincos(0); }
void fn_cos(void) { sincos(1); }

void fn_tan(void)
{
    f_st(&fx);                               /* keep x (fn_sin clobbers fx) */
    {
        static num_t tx, ts;
        num_t *px = &tx, *ps = &ts;
        f_ld(&fx);
        f_st(px);
        fn_sin();
        f_st(ps);
        f_ld(px);
        fn_cos();
        f_st(px);                            /* cos */
        f_ld(ps);
        f_arg(px);
        f_div();                             /* /0 -> E_DIV0 via fac_err */
    }
}
