/* Shared service state contract (#74).
 * App-linked policy runs serialized on the root stack, not in workers or IRQs.
 * The context test precedes LOCK; leave publishes DIAG before unlocking.
 * LOCK is a non-reentrancy guard, not an interrupt/preemption lock. Owner
 * tables and scheduler identity must match the kernel's fixed records.
 * Keep generation bytes across clearing; reconcile stale owners and exact
 * references, and attempt at most one STOP enqueue per collector turn.
 * Public capacity/status values and deferred message semantics are retained.
 * Hooks gb_owner_current/gb_sysinfo/gb_defer_send/gb_wm_open retain the existing
 * ABI: current mapped identity, stable capability record, copied queued values,
 * and synchronous startup with caller bank/stack restored. The collector is
 * not a transport provider; NETSVC and native network calls remain separate.
 * Bounds below do not prove the full memory map, hardware timing or stack use.
 */
#ifndef GEMBENCH_SERVICE_CONTRACT_H
#define GEMBENCH_SERVICE_CONTRACT_H
#if GB_SERVICE_PROVIDER_CAPACITY != 2 || GB_SERVICE_LEASE_CAPACITY != 3
#error "Retain the public service capacities"
#endif
#if GB_SERVICE_OWNER_MAX < 1 || GB_SERVICE_OWNER_MAX > 255
#error "Invalid service owner capacity"
#endif
#define SERVICE_FIXED(a, n) (((a) >= 0 && (a) + (n) <= 0x4000L) || ((a) >= 0x8000L && (a) + (n) <= 0x10000L))
#if !SERVICE_FIXED(GB_SERVICE_PROVIDER_ADDRESS, GB_SERVICE_PROVIDER_CAPACITY * 7)
#error "GB_SERVICE_PROVIDER_ADDRESS must fit fixed address space"
#endif
#if !SERVICE_FIXED(GB_SERVICE_LEASE_ADDRESS, GB_SERVICE_LEASE_CAPACITY * 4)
#error "GB_SERVICE_LEASE_ADDRESS must fit fixed address space"
#endif
#if !SERVICE_FIXED(GB_SERVICE_LOCK_ADDRESS, 1)
#error "GB_SERVICE_LOCK_ADDRESS must fit fixed address space"
#endif
#if !SERVICE_FIXED(GB_SERVICE_DIAG_ADDRESS, 1)
#error "GB_SERVICE_DIAG_ADDRESS must fit fixed address space"
#endif
#if !SERVICE_FIXED(GB_SERVICE_OWNER_ACTIVE_ADDRESS, GB_SERVICE_OWNER_MAX)
#error "GB_SERVICE_OWNER_ACTIVE_ADDRESS must fit fixed address space"
#endif
#if !SERVICE_FIXED(GB_SERVICE_OWNER_GEN_ADDRESS, GB_SERVICE_OWNER_MAX)
#error "GB_SERVICE_OWNER_GEN_ADDRESS must fit fixed address space"
#endif
#if !SERVICE_FIXED(GB_SERVICE_SCHED_ADDRESS, 1)
#error "GB_SERVICE_SCHED_ADDRESS must fit fixed address space"
#endif
#define SERVICE_DISJOINT(a, n, b, m) ((a) + (n) <= (b) || (b) + (m) <= (a))
#if !SERVICE_DISJOINT(GB_SERVICE_PROVIDER_ADDRESS, GB_SERVICE_PROVIDER_CAPACITY * 7, GB_SERVICE_LEASE_ADDRESS, GB_SERVICE_LEASE_CAPACITY * 4)
#error "GB_SERVICE_PROVIDER_ADDRESS overlaps GB_SERVICE_LEASE_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_PROVIDER_ADDRESS, GB_SERVICE_PROVIDER_CAPACITY * 7, GB_SERVICE_LOCK_ADDRESS, 1)
#error "GB_SERVICE_PROVIDER_ADDRESS overlaps GB_SERVICE_LOCK_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_PROVIDER_ADDRESS, GB_SERVICE_PROVIDER_CAPACITY * 7, GB_SERVICE_DIAG_ADDRESS, 1)
#error "GB_SERVICE_PROVIDER_ADDRESS overlaps GB_SERVICE_DIAG_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_PROVIDER_ADDRESS, GB_SERVICE_PROVIDER_CAPACITY * 7, GB_SERVICE_OWNER_ACTIVE_ADDRESS, GB_SERVICE_OWNER_MAX)
#error "GB_SERVICE_PROVIDER_ADDRESS overlaps GB_SERVICE_OWNER_ACTIVE_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_PROVIDER_ADDRESS, GB_SERVICE_PROVIDER_CAPACITY * 7, GB_SERVICE_OWNER_GEN_ADDRESS, GB_SERVICE_OWNER_MAX)
#error "GB_SERVICE_PROVIDER_ADDRESS overlaps GB_SERVICE_OWNER_GEN_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_PROVIDER_ADDRESS, GB_SERVICE_PROVIDER_CAPACITY * 7, GB_SERVICE_SCHED_ADDRESS, 1)
#error "GB_SERVICE_PROVIDER_ADDRESS overlaps GB_SERVICE_SCHED_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_LEASE_ADDRESS, GB_SERVICE_LEASE_CAPACITY * 4, GB_SERVICE_LOCK_ADDRESS, 1)
#error "GB_SERVICE_LEASE_ADDRESS overlaps GB_SERVICE_LOCK_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_LEASE_ADDRESS, GB_SERVICE_LEASE_CAPACITY * 4, GB_SERVICE_DIAG_ADDRESS, 1)
#error "GB_SERVICE_LEASE_ADDRESS overlaps GB_SERVICE_DIAG_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_LEASE_ADDRESS, GB_SERVICE_LEASE_CAPACITY * 4, GB_SERVICE_OWNER_ACTIVE_ADDRESS, GB_SERVICE_OWNER_MAX)
#error "GB_SERVICE_LEASE_ADDRESS overlaps GB_SERVICE_OWNER_ACTIVE_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_LEASE_ADDRESS, GB_SERVICE_LEASE_CAPACITY * 4, GB_SERVICE_OWNER_GEN_ADDRESS, GB_SERVICE_OWNER_MAX)
#error "GB_SERVICE_LEASE_ADDRESS overlaps GB_SERVICE_OWNER_GEN_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_LEASE_ADDRESS, GB_SERVICE_LEASE_CAPACITY * 4, GB_SERVICE_SCHED_ADDRESS, 1)
#error "GB_SERVICE_LEASE_ADDRESS overlaps GB_SERVICE_SCHED_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_LOCK_ADDRESS, 1, GB_SERVICE_DIAG_ADDRESS, 1)
#error "GB_SERVICE_LOCK_ADDRESS overlaps GB_SERVICE_DIAG_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_LOCK_ADDRESS, 1, GB_SERVICE_OWNER_ACTIVE_ADDRESS, GB_SERVICE_OWNER_MAX)
#error "GB_SERVICE_LOCK_ADDRESS overlaps GB_SERVICE_OWNER_ACTIVE_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_LOCK_ADDRESS, 1, GB_SERVICE_OWNER_GEN_ADDRESS, GB_SERVICE_OWNER_MAX)
#error "GB_SERVICE_LOCK_ADDRESS overlaps GB_SERVICE_OWNER_GEN_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_LOCK_ADDRESS, 1, GB_SERVICE_SCHED_ADDRESS, 1)
#error "GB_SERVICE_LOCK_ADDRESS overlaps GB_SERVICE_SCHED_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_DIAG_ADDRESS, 1, GB_SERVICE_OWNER_ACTIVE_ADDRESS, GB_SERVICE_OWNER_MAX)
#error "GB_SERVICE_DIAG_ADDRESS overlaps GB_SERVICE_OWNER_ACTIVE_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_DIAG_ADDRESS, 1, GB_SERVICE_OWNER_GEN_ADDRESS, GB_SERVICE_OWNER_MAX)
#error "GB_SERVICE_DIAG_ADDRESS overlaps GB_SERVICE_OWNER_GEN_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_DIAG_ADDRESS, 1, GB_SERVICE_SCHED_ADDRESS, 1)
#error "GB_SERVICE_DIAG_ADDRESS overlaps GB_SERVICE_SCHED_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_OWNER_ACTIVE_ADDRESS, GB_SERVICE_OWNER_MAX, GB_SERVICE_OWNER_GEN_ADDRESS, GB_SERVICE_OWNER_MAX)
#error "GB_SERVICE_OWNER_ACTIVE_ADDRESS overlaps GB_SERVICE_OWNER_GEN_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_OWNER_ACTIVE_ADDRESS, GB_SERVICE_OWNER_MAX, GB_SERVICE_SCHED_ADDRESS, 1)
#error "GB_SERVICE_OWNER_ACTIVE_ADDRESS overlaps GB_SERVICE_SCHED_ADDRESS"
#endif
#if !SERVICE_DISJOINT(GB_SERVICE_OWNER_GEN_ADDRESS, GB_SERVICE_OWNER_MAX, GB_SERVICE_SCHED_ADDRESS, 1)
#error "GB_SERVICE_OWNER_GEN_ADDRESS overlaps GB_SERVICE_SCHED_ADDRESS"
#endif
#undef SERVICE_FIXED
#undef SERVICE_DISJOINT
#endif
