#!/usr/bin/env bash
# Build the two-disk 720K MSX2 distribution.
#
# GEOBENCH.DSK is bootable on a machine with a Nextor kernel ROM. It
# carries NEXTOR.SYS, COMMAND2.COM, the mode loaders, and the complete GBENCH
# system directory. EXTRAS.DSK carries the picture gallery. Keeping PICS on the
# second disk avoids FAT12 cluster overhead overflowing the boot disk.
#
# Usage: tools/build_msx_floppy.sh [staging-dir] [output-dir]
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="${1:-QA/MSX}"
OUT="${2:-QA/MSX/Floppies}"
DEPS="${MSX_DEPS:-QA/MSXDEPS}"
BOOT_SECTOR="assets/msx/MSXDOS2.BIN"
NEXTOR_LICENSE="docs/licenses/NEXTOR.md"
UNAPI_LICENSE="docs/licenses/OPENMSXNET.md"
MAIN="$OUT/GEOBENCH.DSK"
EXTRAS="$OUT/EXTRAS.DSK"

# Prefer an explicit override, including an empty one for a deliberately
# network-free local disk. Clean release staging does not contain ignored
# binaries, so fall back to the fetched dependency directory.
if [ "${MSX_UNAPI_TSR+x}" = x ]; then
    UNAPI_TSR="$MSX_UNAPI_TSR"
elif [ -s "$SRC/UNAPINET.COM" ]; then
    UNAPI_TSR="$SRC/UNAPINET.COM"
elif [ -s "$DEPS/UNAPINET.COM" ]; then
    UNAPI_TSR="$DEPS/UNAPINET.COM"
else
    UNAPI_TSR=
fi

for tool in mkfs.fat mcopy mdir dd; do
    command -v "$tool" >/dev/null || {
        echo "ERROR: missing '$tool' (install dosfstools and mtools)" >&2
        exit 1
    }
done
for file in NEXTOR.SYS COMMAND2.COM; do
    [ -s "$DEPS/$file" ] || {
        echo "ERROR: $DEPS/$file missing - run tools/fetch_msx_deps.sh" >&2
        exit 1
    }
done
for file in "$BOOT_SECTOR" "$NEXTOR_LICENSE"; do
    [ -s "$file" ] || { echo "ERROR: missing $file" >&2; exit 1; }
done
for path in "$SRC/GBENCH" "$SRC/PICS" "$SRC/DIAG"; do
    [ -d "$path" ] || {
        echo "ERROR: $path missing - run tools/build_kernel_msx.sh" >&2
        exit 1
    }
done

mkdir -p "$OUT"
export MTOOLS_SKIP_CHECK=1

make_disk() { # image label
    local image="$1" label="$2"
    rm -f "$image"
    mkfs.fat --invariant -F12 -S512 -s2 -R1 -f2 -r112 -g 2/9 -h0 \
        -n "$label" -C "$image" 720 >/dev/null
    # Keep only mkfs.fat's matching BPB (bytes 11..29). Install the MSX jump/OEM
    # bytes and the canonical MSX-DOS 2 code/extended block generated by
    # openMSX 21. Keeping mkfs.fat's x86 jump here makes the disk unbootable.
    dd if="$BOOT_SECTOR" of="$image" bs=1 count=11 conv=notrunc status=none
    dd if="$BOOT_SECTOR" of="$image" bs=1 skip=30 seek=30 count=482 \
        conv=notrunc status=none
}

copy_root_files() {
    local image="$1" path name
    for path in "$SRC"/*; do
        [ -f "$path" ] || continue
        name="$(basename "$path")"
        case "$name" in
            AUTOEXEC.BAT|UNAPINET.COM|UNAPI.TXT) continue ;;
        esac
        mcopy -o -i "$image" "$path" ::/
    done
}

make_disk "$MAIN" GBMSX
mcopy -i "$MAIN" "$DEPS/NEXTOR.SYS" ::NEXTOR.SYS
mcopy -i "$MAIN" "$DEPS/COMMAND2.COM" ::COMMAND2.COM
mcopy -i "$MAIN" "$NEXTOR_LICENSE" ::NEXTOR.TXT
copy_root_files "$MAIN"
AUTOEXEC="$(mktemp)"
trap 'rm -f "$AUTOEXEC"' EXIT
if [ -n "$UNAPI_TSR" ]; then
    [ -s "$UNAPI_TSR" ] || {
        echo "ERROR: MSX_UNAPI_TSR not found: $UNAPI_TSR" >&2
        exit 1
    }
    [ -s "$UNAPI_LICENSE" ] || {
        echo "ERROR: missing $UNAPI_LICENSE" >&2
        exit 1
    }
    mcopy -i "$MAIN" "$UNAPI_TSR" ::UNAPINET.COM
    mcopy -i "$MAIN" "$UNAPI_LICENSE" ::UNAPI.TXT
    printf 'UNAPINET\r\nGBMSX\r\n' > "$AUTOEXEC"
    NETWORK_STATUS="TCP/IP UNAPI enabled"
else
    printf 'GBMSX\r\n' > "$AUTOEXEC"
    NETWORK_STATUS="network disabled"
fi
mcopy -i "$MAIN" "$AUTOEXEC" ::AUTOEXEC.BAT
mcopy -s -i "$MAIN" "$SRC/GBENCH" ::/
mcopy -s -i "$MAIN" "$SRC/DIAG" ::/

make_disk "$EXTRAS" GBEXTRAS
mcopy -s -i "$EXTRAS" "$SRC/PICS" ::/

echo "Built $MAIN (Nextor boot + complete GEOBENCH system; $NETWORK_STATUS)"
echo "Built $EXTRAS (picture gallery)"
mdir -i "$MAIN" :: | tail -n 2
mdir -i "$EXTRAS" :: | tail -n 2
