#!/usr/bin/env python3
"""Generate an app-specific subset of the GEOBENCH assembly ABI trampolines.

ASxxxx retains a complete assembly object even when only a few exported labels
are referenced. Memory-constrained applications can list the gb_* entry points
they use in a manifest and link the generated object instead of all of gblib.s.

Usage:
    gblib_subset.py [--interrupt-safe] lib/gb/gblib.s build/GBLIBAPP.s app/gblib.symbols [...]
"""

import re
import sys
from pathlib import Path


def read_symbol_file(path):
    symbols = []
    for line in Path(path).read_text(encoding="ascii").splitlines():
        name = line.split("#", 1)[0].strip()
        if not name:
            continue
        if name.startswith("_gb_"):
            name = name[1:]
        if not re.fullmatch(r"gb_[a-z0-9_]+", name):
            raise ValueError(f"{path}: invalid ABI symbol {name!r}")
        symbols.append("_" + name)
    if not symbols:
        raise ValueError(f"{path}: empty ABI symbol manifest")
    return symbols


def read_symbols(paths):
    symbols = []
    for path in paths:
        symbols.extend(read_symbol_file(path))
    return symbols


def generate(source_path, manifest_paths, *, interrupt_safe=False):
    lines = Path(source_path).read_text(encoding="ascii").splitlines(keepends=True)
    wanted = set(read_symbols(manifest_paths))
    starts = []
    for index, line in enumerate(lines):
        match = re.match(r"^(_gb_[A-Za-z0-9_]+):", line)
        if match:
            starts.append((index, match.group(1)))
    starts.append((len(lines), ""))

    blocks = {}
    for item in range(len(starts) - 1):
        begin, name = starts[item]
        blocks[name] = lines[begin:starts[item + 1][0]]

    missing = wanted - blocks.keys()
    if missing:
        raise ValueError(
            f"{', '.join(map(str, manifest_paths))}: symbols absent from "
            f"{source_path}: "
            + ", ".join(sorted(missing))
        )

    output = [
        ";; Generated by tools/gblib_subset.py; edit the symbol manifest.\n",
        "        .module gblib_subset\n",
    ]
    for name in sorted(wanted):
        output.append(f"        .globl  {name}\n")
    output += [
        "\n        .area   _BSS\n",
        "sv_ret: .ds     2\n",
        "\n        .area   _CODE\n\n",
    ]
    for _, name in starts[:-1]:
        if name in wanted:
            block = "".join(blocks[name])
            if interrupt_safe and name in ('_gb_fill', '_gb_frame', '_gb_icon', '_gb_icon_half'):
                # POP HL / DEC SP consumes one byte by temporarily popping two.
                # An IM1 interrupt in that gap overwrites the next live stack
                # byte with its return PC. Read BEFORE advancing SP instead.
                # Only L is used; A, BC, DE, IX and IY must survive this read.
                block, count = re.subn(
                    r"(?m)^        pop\s+hl[^\n]*\n        dec\s+sp[^\n]*\n",
                    "        ld      hl, #0          ; interrupt-safe one-byte argument\n"
                    "        add     hl, sp\n"
                    "        ld      l, (hl)\n"
                    "        inc     sp\n", block)
                if count != 1:
                    raise ValueError('native stack wrapper changed: '+name)
            output.append(block)
    return "".join(output)


def main(argv):
    interrupt_safe = len(argv) > 1 and argv[1] == '--interrupt-safe'
    if interrupt_safe:
        argv = [argv[0], *argv[2:]]
    if len(argv) < 4:
        raise SystemExit(
            "usage: gblib_subset.py [--interrupt-safe] <gblib.s> <output.s> <symbols-file> [...]"
        )
    source, output, *manifests = argv[1:]
    symbols = set(read_symbols(manifests))
    generated = generate(source, manifests, interrupt_safe=interrupt_safe)
    target = Path(output)
    if target.exists() and target.read_text(encoding="ascii") == generated:
        print(f"{output}: current")
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(generated, encoding="ascii")
    print(f"{output}: {len(symbols)} ABI trampolines")


if __name__ == "__main__":
    try:
        main(sys.argv)
    except (OSError, ValueError) as error:
        raise SystemExit(error)
