#!/usr/bin/env python3
"""Validate the bounded Desk accessory catalog and emit its target C header."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys


MAX_CAPACITY = 10
SYMBOL_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")
APP_RE = re.compile(r"^([A-Z0-9_]{1,8})\.APP$")


class CatalogError(ValueError):
    pass


def _require_int(value: object, field: str, low: int, high: int) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise CatalogError(f"{field} must be an integer")
    if value < low or value > high:
        raise CatalogError(f"{field} must be in {low}..{high}")
    return value


def load_catalog(path: Path) -> tuple[int, list[dict[str, object]]]:
    try:
        root = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise CatalogError(str(error)) from error
    if not isinstance(root, dict) or set(root) != {"capacity", "accessories"}:
        raise CatalogError("catalog must contain only capacity and accessories")
    capacity = _require_int(root["capacity"], "capacity", 1, MAX_CAPACITY)
    source = root["accessories"]
    if not isinstance(source, list) or not source:
        raise CatalogError("accessories must be a non-empty array")
    if len(source) > capacity:
        raise CatalogError(f"catalog has {len(source)} entries but capacity is {capacity}")

    entries: list[dict[str, object]] = []
    ids: set[int] = set()
    symbols: set[str] = set()
    apps: set[str] = set()
    for index, raw in enumerate(source):
        prefix = f"accessories[{index}]"
        if not isinstance(raw, dict) or set(raw) != {"symbol", "id", "label", "app"}:
            raise CatalogError(f"{prefix} must contain only symbol, id, label, and app")
        symbol = raw["symbol"]
        label = raw["label"]
        app = raw["app"]
        identity = _require_int(raw["id"], f"{prefix}.id", 1, 255)
        if not isinstance(symbol, str) or not SYMBOL_RE.fullmatch(symbol):
            raise CatalogError(f"{prefix}.symbol must be an uppercase C identifier")
        if not isinstance(label, str) or not 1 <= len(label) <= 20:
            raise CatalogError(f"{prefix}.label must contain 1..20 characters")
        if any(ord(ch) < 32 or ord(ch) > 126 for ch in label):
            raise CatalogError(f"{prefix}.label must contain printable ASCII only")
        if not isinstance(app, str) or not APP_RE.fullmatch(app):
            raise CatalogError(f"{prefix}.app must be an uppercase 1..8 character .APP name")
        if identity in ids:
            raise CatalogError(f"duplicate accessory id {identity}")
        if symbol in symbols:
            raise CatalogError(f"duplicate accessory symbol {symbol}")
        if app in apps:
            raise CatalogError(f"duplicate accessory app {app}")
        ids.add(identity)
        symbols.add(symbol)
        apps.add(app)
        stem = APP_RE.fullmatch(app).group(1)  # type: ignore[union-attr]
        entries.append(
            {
                "symbol": symbol,
                "id": identity,
                "label": label,
                "app11": f"{stem:<8}APP",
            }
        )
    return capacity, entries


def render_header(capacity: int, entries: list[dict[str, object]]) -> str:
    lines = [
        "/* Generated by tools/gen_desk_accessories.py; do not edit. */",
        "#ifndef GEMBENCH_GENERATED_GBDESK_CATALOG_H",
        "#define GEMBENCH_GENERATED_GBDESK_CATALOG_H",
        "",
        f"#define GB_DESK_ACCESSORY_CAPACITY {capacity}u",
        f"#define GB_DESK_ACCESSORY_COUNT {len(entries)}u",
    ]
    for index, entry in enumerate(entries):
        symbol = entry["symbol"]
        lines.append(f"#define GB_DESK_ACCESSORY_{symbol}_ID {entry['id']}u")
        lines.append(f"#define GB_DESK_ACCESSORY_{symbol}_INDEX {index}u")
    lines.extend(
        [
            "",
            "#ifdef GB_DESK_CATALOG_DATA",
            "static const char *const gb_desk_accessory_labels[GB_DESK_ACCESSORY_COUNT] = {",
        ]
    )
    for entry in entries:
        lines.append(f"    {json.dumps(entry['label'])},")
    lines.extend(
        [
            "};",
            "static const unsigned char gb_desk_accessory_ids[GB_DESK_ACCESSORY_COUNT] = {",
        ]
    )
    lines.append("    " + ", ".join(f"{entry['id']}u" for entry in entries))
    lines.extend(
        [
            "};",
            "static const char gb_desk_accessory_apps[GB_DESK_ACCESSORY_COUNT][12] = {",
        ]
    )
    for entry in entries:
        lines.append(f"    {json.dumps(entry['app11'])},")
    lines.extend(
        [
            "};",
            "#endif /* GB_DESK_CATALOG_DATA */",
            "",
            "#endif /* GEMBENCH_GENERATED_GBDESK_CATALOG_H */",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        capacity, entries = load_catalog(args.source)
        rendered = render_header(capacity, entries)
    except CatalogError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except OSError:
            current = ""
        if current != rendered:
            print(f"ERROR: {args.output} is not current; regenerate it", file=sys.stderr)
            return 1
        print(f"{args.output}: current ({len(entries)}/{capacity} accessories)")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
        args.output.write_text(rendered, encoding="utf-8")
    print(f"{args.output}: {len(entries)}/{capacity} accessories")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
