#!/usr/bin/env python3
"""Generate apps/telnet/charset4.h - a 4x8 ASCII charset (chars 32..127) for the
PCW TELNET direct-framebuffer renderer (80x25 windowed / 90x31 fullscreen).

The glyphs are derived from tools/genfont.py's 5x7-in-6x8 art: the two middle
columns (2 and 3) are OR-merged, squeezing 5 px to 4. A few glyphs where that
merge muddies the shape carry a hand-drawn 4px override below. Each output
byte is one scan line with the pattern in the LOW nibble (bit 3 = leftmost),
so the renderer can index its nibble->CGA2-byte LUT directly.

  tools/gen_telnet_charset4.py           # -> apps/telnet/charset4.h
  tools/gen_telnet_charset4.py --preview # ASCII-dump every glyph to stdout

Re-run + commit charset4.h if genfont.py's art ever changes.
"""
import importlib.util
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
spec = importlib.util.spec_from_file_location(
    "genfont", os.path.join(root, "tools", "genfont.py"))
genfont = importlib.util.module_from_spec(spec)
spec.loader.exec_module(genfont)

# Hand-drawn 4px overrides where the 5->4 column merge loses the shape
# (mostly glyphs whose middle columns carry distinct strokes). 8 rows of
# exactly 4 chars, '#' = pixel on.
OVERRIDE = {
    'M': ["#..#",
          "####",
          "####",
          "#..#",
          "#..#",
          "#..#",
          "#..#"],
    'W': ["#..#",
          "#..#",
          "#..#",
          "#..#",
          "####",
          "####",
          "#..#"],
    'm': ["....",
          "....",
          "###.",
          "####",
          "#.##",
          "#.##",
          "#..#"],
    'w': ["....",
          "....",
          "#..#",
          "#..#",
          "####",
          "####",
          ".##."],
    '#': [".#.#",
          "####",
          ".#.#",
          ".#.#",
          "####",
          "#.#.",
          "...."],
    '%': ["#..#",
          "...#",
          "..#.",
          ".#..",
          "#...",
          "#..#",
          "...."],
    '@': [".##.",
          "#..#",
          "#.##",
          "#.##",
          "#...",
          ".##.",
          "...."],
    '~': ["....",
          "....",
          ".#.#",
          "#.#.",
          "....",
          "....",
          "...."],
}


def rows_of(code):
    ch = chr(code)
    if ch in OVERRIDE:
        rows = OVERRIDE[ch]
        return [(r + "....")[:4] for r in rows] + ["...."] * (8 - len(rows))
    art = genfont.G.get(ch, [])
    out = []
    for i in range(8):
        row = (art[i] + ".....")[:5] if i < len(art) else "....."
        p = [c == '#' for c in row]
        out.append("".join('#' if b else '.'
                           for b in (p[0], p[1], p[2] or p[3], p[4])))
    return out


def main(argv):
    if len(argv) > 1 and argv[1] == '--preview':
        for code in range(32, 127):
            print(f"--- {code} '{chr(code)}'")
            for r in rows_of(code):
                print("   ", r.replace('.', ' '))
        return
    out = os.path.join(root, "apps", "telnet", "charset4.h")
    with open(out, "w") as f:
        f.write("/* charset4.h - 4x8 ASCII glyphs (chars 32..127) for the PCW TELNET\n")
        f.write(" * direct-framebuffer renderer (80x25 windowed / 90x31 fullscreen).\n")
        f.write(" * GENERATED by tools/gen_telnet_charset4.py from tools/genfont.py's\n")
        f.write(" * glyph art - do not edit by hand. Each glyph = 8 bytes (one per scan\n")
        f.write(" * line), pattern in the LOW nibble, bit 3 = leftmost pixel. */\n")
        f.write("#ifndef TELNET_CHARSET4_H\n#define TELNET_CHARSET4_H\n")
        f.write("#define FS4_GLYPH0 32\n")
        f.write("static const unsigned char fs4_charset[96 * 8] = {\n")
        for code in range(32, 128):
            rows = rows_of(code) if code < 127 else ["...."] * 8
            vals = []
            for r in rows:
                n = 0
                for i, c in enumerate(r):
                    if c == '#':
                        n |= 8 >> i
                vals.append(n)
            name = chr(code) if 32 < code < 127 else ("SP" if code == 32 else "DEL")
            f.write("    " + ", ".join(f"0x{v:02X}" for v in vals)
                    + f",   /* '{name}' */\n")
        f.write("};\n#endif\n")
    print(f"{out}: 96 glyphs 4x8")


if __name__ == '__main__':
    main(sys.argv)
