#!/usr/bin/env python3
"""Generate the reversible native-byte lookup tables for portable GBPC pictures."""

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TARGETS = {
    "msx": ROOT / "lib/msx/pic_lut.inc",
    "pcw": ROOT / "lib/pcw/pic_lut.inc",
}


def mode1_to_screen6(byte: int) -> int:
    out = 0
    for pixel in range(4):
        pen = ((byte >> (7 - pixel)) & 1) | (((byte >> (3 - pixel)) & 1) << 1)
        out |= pen << (6 - 2 * pixel)
    return out


def pcw_permute(byte: int) -> int:
    return (((byte & 0x55) << 1) | (((byte ^ 0xFF) & 0xAA) >> 1)) & 0xFF


def tables(target: str) -> tuple[list[int], list[int]]:
    forward = []
    for byte in range(256):
        native = mode1_to_screen6(byte)
        if target == "pcw":
            native = pcw_permute(native)
        forward.append(native)
    if len(set(forward)) != 256:
        raise ValueError(f"{target}: byte mapping is not reversible")
    inverse = [0] * 256
    for canonical, native in enumerate(forward):
        inverse[native] = canonical
    for byte in range(256):
        if inverse[forward[byte]] != byte or forward[inverse[byte]] != byte:
            raise ValueError(f"{target}: lookup round trip failed at {byte:#04x}")
    return forward, inverse


def emit_table(label: str, values: list[int]) -> list[str]:
    lines = ["                align 256", label]
    for offset in range(0, 256, 16):
        row = ",".join(f"#{value:02X}" for value in values[offset:offset + 16])
        lines.append(f"                db    {row}")
    lines.append(f"                assert ({label} & #FF)==0,\"{label} must be page-aligned\"")
    return lines


def render(target: str) -> str:
    forward, inverse = tables(target)
    lines = [
        "; Generated by tools/gen_pic_luts.py. Do not edit by hand.",
        "; Canonical GBPC Mode-1 bytes <-> this platform's raw display bytes.",
        "",
    ]
    lines.extend(emit_table("pic_m1_to_native", forward))
    lines.append("")
    lines.extend(emit_table("pic_native_to_m1", inverse))
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    stale = []
    for target, path in TARGETS.items():
        expected = render(target)
        if args.check:
            if not path.exists() or path.read_text() != expected:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(expected)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        sys.exit("stale generated PIC lookup tables: " + ", ".join(stale))


if __name__ == "__main__":
    main()
