#!/usr/bin/env python3
"""png2cpc - convert a small 4-colour PNG into an Amstrad CPC Mode 1 bitmap.

Mode 1 packs 4 pixels per byte (2 bits each). Each pixel's pen (0..3) is split
across the byte: pen bit0 goes to the high nibble, pen bit1 to the low nibble.

    pixel 0: bit7 = pen bit0, bit3 = pen bit1
    pixel 1: bit6 / bit2
    pixel 2: bit5 / bit1
    pixel 3: bit4 / bit0

Each PNG pixel is mapped to the nearest of four reference colours (the GEOBENCH
desktop palette), which become pens 0..3:

    pen 0  blue   (backdrop / transparent)   #000080
    pen 1  white                             #FFFFFF
    pen 2  black                             #000000
    pen 3  red                               #FF0000

Output is a RASM-includable .asm file: a label, <label>_w (width in BYTES),
<label>_h (height in rows), and the row-major encoded bytes.

Usage:
    tools/png2cpc.py <in.png> <out.asm> <label> [WxH]

If WxH is given the image is resized (Lanczos) to that size first, so a large
source art file can be reduced to icon size in one step. Width must end up a
multiple of 4.
"""
import sys
from PIL import Image

# Reference palette -> pen index. Edit/extend if the desktop palette changes.
PALETTE = [
    ((0x00, 0x00, 0x80), 0),   # blue (backdrop)
    ((0xFF, 0xFF, 0xFF), 1),   # white
    ((0x00, 0x00, 0x00), 2),   # black
    ((0xFF, 0x00, 0x00), 3),   # red
]

# Which screen bits carry pen bit0 / pen bit1 for each of the 4 pixels in a byte.
BIT0_FOR_PIXEL = (7, 6, 5, 4)
BIT1_FOR_PIXEL = (3, 2, 1, 0)


def nearest_pen(rgb):
    best, best_d = 0, None
    for (r, g, b), pen in PALETTE:
        d = (r - rgb[0]) ** 2 + (g - rgb[1]) ** 2 + (b - rgb[2]) ** 2
        if best_d is None or d < best_d:
            best, best_d = pen, d
    return best


def encode_byte(pens4):
    """pens4: list of up to 4 pen values (0..3), left to right -> one byte."""
    byte = 0
    for i, pen in enumerate(pens4):
        if pen & 1:
            byte |= 1 << BIT0_FOR_PIXEL[i]
        if pen & 2:
            byte |= 1 << BIT1_FOR_PIXEL[i]
    return byte


def main():
    if len(sys.argv) not in (4, 5):
        print(__doc__)
        sys.exit(2)
    in_png, out_asm, label = sys.argv[1], sys.argv[2], sys.argv[3]

    img = Image.open(in_png).convert("RGB")
    if len(sys.argv) == 5:
        tw, th = (int(v) for v in sys.argv[4].lower().split("x"))
        img = img.resize((tw, th), Image.LANCZOS)
    w, h = img.size
    if w % 4 != 0:
        print(f"error: width {w} is not a multiple of 4 (4 pixels per byte)")
        sys.exit(1)
    wbytes = w // 4

    px = img.load()
    used = {}
    rows = []
    for y in range(h):
        row = []
        for bx in range(wbytes):
            pens = []
            for i in range(4):
                pen = nearest_pen(px[bx * 4 + i, y])
                pens.append(pen)
                used[pen] = used.get(pen, 0) + 1
            row.append(encode_byte(pens))
        rows.append(row)

    if out_asm.lower().endswith(".bin"):
        # Raw row-major Mode-1 bytes (no header) - what restore_block blits directly.
        # The consumer hard-codes the width/height, so they're only reported here.
        with open(out_asm, "wb") as f:
            for row in rows:
                f.write(bytes(row))
    else:
        with open(out_asm, "w") as f:
            f.write(f"; generated by png2cpc from {in_png} ({w}x{h} px)\n")
            f.write(f"{label}_w       equ   {wbytes}            ; width in bytes ({w}px)\n")
            f.write(f"{label}_h       equ   {h}            ; height in rows\n")
            f.write(f"{label}\n")
            for row in rows:
                f.write("                db    " + ",".join(f"#{b:02X}" for b in row) + "\n")

    names = {0: "blue", 1: "white", 2: "black", 3: "red"}
    report = ", ".join(f"pen{p} {names[p]}={used.get(p,0)}" for p in range(4))
    print(f"{in_png}: {w}x{h} -> {wbytes}x{h} bytes ({wbytes*h} B), {label}  [{report}]")


if __name__ == "__main__":
    main()
