from PIL import Image
import math
SRC='/var/home/salvogendut/Dev/geobench/assets/catclockbody.png'
OUTH='/var/home/salvogendut/Dev/geobench/apps/catclock/catimg.h'
im=Image.open(SRC).convert('RGB')   # full size 101x201
TW,TH0=im.size; px=im.load()
X0COL=27; X0=X0COL*4; CAT_H=200      # drop the 201st row to fit screen
def cls(p):
    r,g,b=p
    if r>140 and g<90 and b<90:return 3   # red -> pen3 (bow tie)
    if b>140 and r<120:return 0            # blue -> pen0 (background)
    if r>150 and g>150:return 1            # white -> pen1
    return 2                                # black -> pen2
grid=[[cls(px[x,y]) for x in range(TW)] for y in range(CAT_H)]
BPR=(TW+3)//4
# connected components (white) for dial + eyes
seen=[[False]*TW for _ in range(CAT_H)];comps=[]
for y0 in range(CAT_H):
    for x0 in range(TW):
        if grid[y0][x0]==1 and not seen[y0][x0]:
            st=[(x0,y0)];seen[y0][x0]=True;pts=[]
            while st:
                x,y=st.pop();pts.append((x,y))
                for dx,dy in((1,0),(-1,0),(0,1),(0,-1)):
                    nx,ny=x+dx,y+dy
                    if 0<=nx<TW and 0<=ny<CAT_H and grid[ny][nx]==1 and not seen[ny][nx]:
                        seen[ny][nx]=True;st.append((nx,ny))
            comps.append(pts)
def bbox(p):
    xs=[a for a,b in p];ys=[b for a,b in p];return min(xs),min(ys),max(xs),max(ys)
dial=max((c for c in comps if bbox(c)[0]>1 and bbox(c)[2]<TW-2 and (bbox(c)[1]+bbox(c)[3])//2>CAT_H*0.45 and len(c)>400),key=len)
dx0,dy0,dx1,dy1=bbox(dial)
CLK_CX=X0+(dx0+dx1)//2; CLK_CY=(dy0+dy1)//2; CLK_R=min((dx1-dx0)//2,(dy1-dy0)//2)
eyes=sorted([((bbox(c)[0]+bbox(c)[2])//2,(bbox(c)[1]+bbox(c)[3])//2) for c in comps
             if (bbox(c)[1]+bbox(c)[3])//2<CAT_H*0.30 and 30<len(c)<700],key=lambda e:e[0])
EL=(X0+eyes[0][0],eyes[0][1]); ER=(X0+eyes[-1][0],eyes[-1][1])
# pack CPC mode-1
packed=[]
for y in range(CAT_H):
    for bc in range(BPR):
        b=0
        for n in range(4):
            x=bc*4+n; pen=grid[y][x] if x<TW else 0
            if pen&1:b|=0x80>>n
            if pen&2:b|=0x08>>n
        packed.append(b)
# byte-col restore rects
def colrange(cx,half):return (max(0,(cx-X0-half)//4), min(BPR-1,(cx-X0+half)//4))
elc=colrange(EL[0],9); erc=colrange(ER[0],9); dlc=(dx0//4,dx1//4)
with open(OUTH,'w') as f:
    f.write('/* Generated by tools/png2catclock.py from assets/catclockbody.png - do not edit. */\n')
    f.write('#define CAT_BPR %d\n#define CAT_H %d\n#define CAT_X0COL %d\n'%(BPR,CAT_H,X0COL))
    f.write('#define CLK_CX %d\n#define CLK_CY %d\n#define CLK_R %d\n'%(CLK_CX,CLK_CY,CLK_R))
    f.write('#define EYE_LX %d\n#define EYE_RX %d\n#define EYE_LY %d\n#define EYE_RY %d\n'%(EL[0],ER[0],EL[1],ER[1]))
    f.write('#define EYE_L_C0 %d\n#define EYE_L_C1 %d\n#define EYE_R_C0 %d\n#define EYE_R_C1 %d\n'%(elc[0],elc[1],erc[0],erc[1]))
    f.write('#define EYE_R0 %d\n#define EYE_R1 %d\n'%(min(EL[1],ER[1])-9,max(EL[1],ER[1])+9))
    f.write('#define DIAL_C0 %d\n#define DIAL_C1 %d\n#define DIAL_R0 %d\n#define DIAL_R1 %d\n'%(dlc[0],dlc[1],dy0,dy1))
    f.write('static const unsigned char cat_img[%d] = {\n'%len(packed))
    for i in range(0,len(packed),20):
        f.write(' '+','.join(str(v) for v in packed[i:i+20])+',\n')
    f.write('};\n')
print('BPR',BPR,'clock',(CLK_CX,CLK_CY),'r',CLK_R,'eyeL',EL,'eyeR',ER,'bytes',len(packed))
print('dial bbox y',dy0,dy1,'cols',dlc)
